### ISSUE TITLE
Usage question regarding the pom file

### ISSUE THREAD

**Issue by jpaulgs** [awslabs/amazon-kinesis-client-ruby#68]
The pom.xml file is not packaged in the gemspec.

I was expecting to pull that from the gem and install the required dependancies from there for my environments.

Is that an oversight or should I copy the pom file to my application and hard lock the version of this gem that I depend on?

**Comment by zengyu714** [comment]
Hi @jpaulgs, `pom.xml` should be part of the `gemspec`, we will release a patch version to fix this, thanks for pointing it out!

**Comment by zengyu714** [comment]
The pom file should now be included in the most recent version of 2.2.1, closing the issue..

**Comment by jpaulgs** [comment]
@zengyu714 the pom file isn't currently a valid pom file.  It's missing a few fields `groupId`, `artifactId` and `version`.  I know that the sample code includes a rake file that downloads the jar files but I figure if I need to install java anyway I can get maven retrieve these.

Would it be possible for a future version to include something like?
```
    <groupId>software.amazon.kinesis</groupId>
    <artifactId>amazon-kinesis-client-ruby-pom</artifactId>
    <version>2.1.0</version>
```

**Comment by zengyu714** [comment]
Hi @jpaulgs, since kcl-ruby is essentially a wrapper for [kcl-java](https://github.com/awslabs/amazon-kinesis-client), in order to use it, you need to download the necessary jars (as done in the Rakefile) and have Java installed on your system.


> Would it be possible for a future version to include something like?

I don't think it is necessary to add the aforementioned lines to the `pom.xml`. While the pom file is primarily used for GitHub dependabot, it is not a crucial tool for managing dependencies in `kcl-ruby`.
